cmd/root.go, formatter/config.go, formatter/file.go, formatter/format.go, formatter/format_test.go, formatter/formatter.go, formatter/formatter_csv.go, formatter/formatter_html.go, formatter/formatter_json.go, formatter/formatter_md.go, formatter/nmap_host.go, formatter/nmap_port.go, formatter/nmap_run.go, formatter/output_options.go, formatter/template_data.go
=> #2: Move types to formatter package

cmd/root.go
=> #10: Remove unused variable from root.go validate function

README.md
=> #6: Add build status badge

README.md, cmd/root.go, formatter/formatter_csv.go, formatter/output_options.go, formatter/resources/templates/markdown.tmpl, formatter/resources/templates/simple-html.gohtml
=> #7: Rename down-hosts output option

README.md
=> #3: Add table of contents to the README

.github/workflows/go.yml, .prettierrc.yml, README.md, cmd/root.go, cmd/root_test.go, formatter/formatter.go, formatter/formatter_csv_test.go, formatter/formatter_html_test.go, formatter/formatter_json_test.go, formatter/formatter_md.go, formatter/formatter_md_test.go, formatter/formatter_test.go, formatter/workflow.go, formatter/workflow_test.go, go.mod, go.sum
=> #12: Increase unit test coverage

.github/workflows/go.yml
=> #9: Add matrix strategy for ci workflow

README.md, cmd/root.go, formatter/formatter_json.go, formatter/formatter_json_test.go, formatter/output_options.go
=> #11: Implement json-pretty print option

README.md
=> #4: Add nmap-formatter examples with jq tool

README.md, cmd/root.go, cmd/root_test.go, formatter/config.go
=> #37: Add version command & flag

.github/release-drafter.yml, .github/workflows/release-drafter.yml, .github/workflows/update-changelog.yml
=> #38: Add release drafter & changelog workflow

.github/workflows/go.yml
=> #41: Add lint stage to the workflow

.github/workflows/release-assets.yml
=> #44: Add release-assets workflow

.github/workflows/assets.yml, .github/workflows/go.yml
=> #48: Update golang to 1.17

README.md
=> Fix "go install" url

cmd/root.go, cmd/root_test.go
* Minor refactoring of show version functionality.
* Added unit tests
=> other: minor refactoring of show version functionality

formatter/formatter_md.go, formatter/formatter_md_test.go, formatter/resources/templates/markdown.tmpl
=> #34: Remove blank vertical spaces in Markdown format

formatter/formatter_csv.go, formatter/formatter_csv_test.go, formatter/formatter_html_test.go, formatter/formatter_json_test.go, formatter/formatter_md_test.go, formatter/nmap_host.go, formatter/nmap_port.go, formatter/nmap_run.go, formatter/resources/templates/markdown.tmpl
=> #60: Change certain fields to integers

.dockerignore, .github/workflows/release-package.yml, Dockerfile
=> #19: Add docker image

.github/workflows/go.yml, cmd/root_test.go, formatter/workflow_test.go
=> #69: Use alternative golangci-lint

cmd/root_test.go
=> #73: Make tests file cleanup non-fatal

README.md
=> #68: Update README about usage (as a library)

LICENSE, cmd/root.go, cmd/root_test.go, main.go
=> Update years in license

README.md, cmd/root.go
=> #88: Change places for file/format arguments

README.md, cmd/root.go, cmd/root_test.go, formatter/config.go, formatter/file.go, formatter/file_test.go, formatter/workflow.go, formatter/workflow_test.go
=> #77: Possibility to read xml content from stdin

cmd/root.go, formatter/output_options.go, formatter/resources/templates/markdown.tmpl
=> #90: Add metrics/traceroute chapters to markdown template

formatter/resources/templates/markdown.tmpl
=> #103: Fix markdown port table missing column

cmd/root.go
=> #118: Add missing 'dot' format in usage text

.github/workflows/codeql-analysis.yml
=> #120: Upgrade CodeQL to v2

formatter/nmap_host.go
=> fix: make OSClass a slice

.github/workflows/assets.yml, .github/workflows/codeql-analysis.yml, .github/workflows/go.yml, .github/workflows/release-package.yml
=> tweak: update pipeline action versions

.github/workflows/codeql-analysis.yml, .github/workflows/go.yml, .github/workflows/release.yml
=> feat: ci: update codeql version

LICENSE, cmd/root.go, cmd/root_test.go, main.go
=> Update license years

cmd/root.go, formatter/config.go, formatter/expr.go, formatter/expr_test.go, formatter/workflow.go, go.mod, go.sum
=> feat: basic implementation for filter expressions
